# Generated by Django 4.2.7 on 2023-12-13 18:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("NLHE", "No-Limit Hold'em"),
                            ("LHE", "Limit Hold'em"),
                            ("PLO-4", "Pot-Limit Omaha Hi-Lo (4 cards)"),
                            ("PLO-5", "Pot-Limit Omaha Hi-Lo (5 cards)"),
                            ("PLO-6", "Pot-Limit Omaha Hi-Lo (6 cards)"),
                            ("PLO hi/lo-4", "Pot-Limit Omaha Hi/Lo (4 cards)"),
                            ("PLO hi/lo-5", "Pot-Limit Omaha Hi/Lo (5 cards)"),
                            ("Dealer's Choice", "Dealer's Choice"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "small_blind",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "big_blind",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bankroll", models.IntegerField(default=0)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "game_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poker_host.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="player_session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buy_in",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("cash_out", models.IntegerField()),
                ("pnl", models.IntegerField()),
                ("notes", models.TextField(max_length=1000)),
                (
                    "player_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poker_host.player",
                    ),
                ),
                (
                    "session_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poker_host.session",
                    ),
                ),
            ],
        ),
    ]
