# Generated by Django 4.2.7 on 2023-12-13 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("poker_host", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="player_session",
            new_name="PlayerSession",
        ),
    ]
