# Generated by Django 4.2.7 on 2023-12-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poker_host", "0002_rename_player_session_playersession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_type",
            field=models.CharField(
                choices=[
                    ("NLHE", "No-Limit Hold'em"),
                    ("LHE", "Limit Hold'em"),
                    ("PLO-4", "Pot-Limit Omaha (4 cards)"),
                    ("PLO-5", "Pot-Limit Omaha (5 cards)"),
                    ("PLO-6", "Pot-Limit Omaha (6 cards)"),
                    ("PLO hi/lo-4", "Pot-Limit Omaha Hi/Lo (4 cards)"),
                    ("PLO hi/lo-5", "Pot-Limit Omaha Hi/Lo (5 cards)"),
                    ("Dealer's Choice", "Dealer's Choice"),
                ],
                max_length=100,
            ),
        ),
    ]
