# Generated by Django 4.2.7 on 2023-12-13 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("poker_host", "0003_alter_game_game_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playersession",
            name="pnl",
        ),
    ]
