# Generated by Django 4.2.7 on 2023-12-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poker_host", "0004_remove_playersession_pnl"),
    ]

    operations = [
        migrations.AddField(
            model_name="playersession",
            name="rebuy",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playersession",
            name="cash_out",
            field=models.IntegerField(default=0),
        ),
    ]
