# Generated by Django 4.2.7 on 2023-12-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poker_host", "0005_playersession_rebuy_alter_playersession_cash_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playersession",
            name="notes",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
