# Generated by Django 4.2.7 on 2023-12-19 07:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("poker_host", "0006_alter_playersession_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playersession",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="playersession",
            name="rebuy",
        ),
        migrations.CreateModel(
            name="RebuyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rebuy_amount",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "player_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poker_host.playersession",
                    ),
                ),
            ],
        ),
    ]
