# Generated by Django 4.2.7 on 2023-12-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poker_host", "0007_remove_playersession_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playersession",
            name="cash_out",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
