# Generated by Django 4.2.7 on 2023-12-19 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("poker_host", "0008_alter_playersession_cash_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rebuyevent",
            name="player_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rebuy_events",
                to="poker_host.playersession",
            ),
        ),
    ]
