# Generated by Django 4.2.7 on 2023-12-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poker_host", "0009_alter_rebuyevent_player_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="duration_hours",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="session",
            name="duration_minutes",
            field=models.IntegerField(default=0),
        ),
    ]
