# Generated by Django 4.2.7 on 2023-12-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poker_host", "0011_alter_playersession_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
