# Generated by Django 4.2.7 on 2023-12-20 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("poker_host", "0012_session_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="playersession",
            name="pnl",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playersession",
            name="session_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_sessions",
                to="poker_host.session",
            ),
        ),
    ]
